project_id = "idqjdxgwvtinlzjdreqf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "storage"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
external_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[functions.zep-memory]
verify_jwt = true

[functions.contract-analysis]
verify_jwt = true

[functions.conversational-ai]
verify_jwt = true

# To enable n8n webhook integration for contract analysis, add your webhook URL as a secret:
# N8N_WEBHOOK_URL = "https://your-n8n-instance.com/webhook/contract-analysis"