// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idqjdxgwvtinlzjdreqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkcWpkeGd3dnRpbmx6amRyZXFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNTAyOTUsImV4cCI6MjA2OTkyNjI5NX0.9H_RUN2_DNAWBMd8f8xlFqGOgS2tcSKw0yWyUHEyYFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});